/* Generated By:JavaCC: Do not edit this line. CCJSqlParserVisitor.java Version 6.1_2 */
package net.sf.jsqlparser.parser;

public interface CCJSqlParserVisitor
{
  public Object visit(SimpleNode node, Object data);
}
/* JavaCC - OriginalChecksum=ea8fe4585a348b9d3f37271a377a2c7d (do not edit this line) */
