/* Generated By:JavaCC: Do not edit this line. CCJSqlParserTreeConstants.java Version 6.1_2 */
package net.sf.jsqlparser.parser;

public interface CCJSqlParserTreeConstants
{
  public int JJTSTATEMENT = 0;
  public int JJTVOID = 1;
  public int JJTSTATEMENTS = 2;
  public int JJTCOLUMN = 3;
  public int JJTTABLE = 4;
  public int JJTEXPRESSION = 5;


  public String[] jjtNodeName = {
    "Statement",
    "void",
    "Statements",
    "Column",
    "Table",
    "Expression",
  };
}
/* JavaCC - OriginalChecksum=d469ff2321db2da2e024bcc778c5bc1d (do not edit this line) */
